### ISSUE TITLE
option to configure the width of the swipe

### ISSUE THREAD

**Issue by PavelPolyakov** [RichardRNStudio/react-native-slider-intro#26]
Good day,

Thank you for this module, I just started to use it and it feels great.
What I also observed, that the width of the swipe to scroll through the scene is quite big. Is there an option to configure it? So swipe happens more in the nature of kinematic scrolling (short, but strong swipe = next slide).

I first thought that `navContainerMaxSizePercent` has relation to it, but it does not seem so.

Thank you, looking forward to your answer.

**Comment by RichardRNStudio** [comment]
Hi @PavelPolyakov, 
I'll have a look on it soon, thank you for your question, it is a good idea to investigate it.

**Comment by RichardRNStudio** [comment]
Hi @PavelPolyakov,
I've implemented the new property: `limitToSlide`
You can find the related documentation in the release notes: <a href="https://github.com/RichardRNStudio/react-native-slider-intro/releases/tag/v2.1.14">`v2.1.14`</a>
The `README.md` has been also updated with the description of the new property.
Please let me know if you experience any issues.

**Comment by PavelPolyakov** [comment]
Thanks for the swift update. Definitely will use that! You are the best 📈

**Comment by RichardRNStudio** [comment]
Thank you @PavelPolyakov 🙏
