### ISSUE TITLE
Icon Instead of IMAGE

### ISSUE THREAD

**Issue by seamive** [RichardRNStudio/react-native-slider-intro#3]
Hello,

Can we use Icon or LottieView instead of an Image?

**Comment by RichardRNStudio** [comment]
Hey @seamive,
You can use the **renderItem** function to render a custom slide. I'll put a new example into the examples folder soon about how you can do this.

**Comment by seamive** [comment]
Sure, please do the needful, have been looking for it a long time.
Also looking if we can make it more materialistic using react-native-paper or something similar.

**Comment by RichardRNStudio** [comment]
Hey @seamive,

I haven't tried the _react-native-paper_, but I think you can make it with the renderItem function. 

The following example will show you how you can customize the layout with **renderItem** function.
[https://github.com/RichardRNStudio/react-native-slider-intro/blob/main/example/src/CustomRenderFunctionExample.js](https://github.com/RichardRNStudio/react-native-slider-intro/blob/main/example/src/CustomRenderFunctionExample.js)

Can I close the issue?

**Comment by seamive** [comment]
Still don't know how to implement Icon or LottieView with this, can you create an example with it? That would be really helpful.

**Comment by RichardRNStudio** [comment]
You can create anything inside the **renderItem** function, did you see the example?

**Comment by seamive** [comment]
Yes, we did see, unable to understand how to properly apply for Icons and LottieView, can you add a feature request to support ICON and LottieView to those?

**Comment by RichardRNStudio** [comment]
Instead of the image on center, right? I'll do it soon.

**Comment by seamive** [comment]
Here are some great feature requests:
1. Support to use Icons like FontAwesome, RN Vector Icons, LottieView instead of "image"
2. Adding customized text and widget like Shimmer Place Holder
3. Adding dynamic text in sliders.

We would love to contribute to the project if we can.

Thanks!

**Comment by seamive** [comment]
@RichardRNStudio: We hope you're doing great, any updates on this?

**Comment by RichardRNStudio** [comment]
@seamive I'm fine, thank you. I hope you're well too. Unfortunately I didn't have enough free time to do this, but I'll make the necessary changes on this weekend! I'll let you know when the code is ready.

**Comment by seamive** [comment]
@RichardRNStudio: any updates?

**Comment by RichardRNStudio** [comment]
@seamive Sorry, I didn't have time to do it, but I'll today afternoon.

**Comment by seamive** [comment]
Sure, thanks!

**Comment by RichardRNStudio** [comment]
@seamive I've created one more example how you can customize the renderItem function with third party libraries. 
The example includes:
- react-native-shimmer-placeholder
- FontAwesome Icon instead of the "image"

So as you can see you can do anything inside this function.

The example: [https://github.com/RichardRNStudio/react-native-slider-intro/blob/main/example/src/UsingThirdPartyLibrariesExample.js](https://github.com/RichardRNStudio/react-native-slider-intro/blob/main/example/src/UsingThirdPartyLibrariesExample.js)

I close the issue, if you have more questions then open a different one.

Best regards,
RNStudio

**Comment by seamive** [comment]
Thank you so much! Though we were really Looking forward to the support of LottieViews, we'll give it a spin ourselves to that! <3

**Comment by seamive** [comment]
Just wanted to confirm if this is right or wrong? https://github.com/RichardRNStudio/react-native-slider-intro/blob/main/example/src/UsingThirdPartyLibrariesExample.js#L157

Also, the styles you have applied in the same file are default ones?

**Comment by RichardRNStudio** [comment]
No, they're not the default ones, and yes it's correct on this example, but you can change/customize all of styles on your way. It's fully customizable.
